name: Build & Release Native AOT

on:
  push:
    tags:
      - 'v*'  # Matches v1.0.0, v2.1.3, etc.

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build using Docker and publish to GitHub Releases
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build aot linux binaries from docker image
        run: ./build/linux-aot/build.sh
        
      - name: Create release files for linux aot tar.gz
        run: |
          cd ./linux-aot-output/publish
          tar -czf ../../linux-aot.tar.gz .

      - name: Build aot windows binaries from docker image
        run: ./build/windows-aot/build.sh
        
      - name: Create release files for windows aot tar.gz
        run: |
          cd ./windows-aot-output/publish
          tar -czf ../../windows-aot.tar.gz .

      - name: Upload binaries to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./linux-aot.tar.gz
            ./windows-aot.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
